spring:
  application:
    name: nacos-consumer-feign
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.210.15:8848
    sentinel:
      transport:
        port: 8720
        dashboard: 172.16.210.15:8080
feign:
  sentinel:
    enabled: true
server:
  port: 9092

management:
  endpoints:
    web:
      exposure:
        include: "*"